root - INFO - Datetime limit: 10/12/2020, 13:30:04
root - INFO - Setting up the instagram and twitter accounts
instabot version: 0.117.0 - INFO - Instabot version: 0.117.0 Started
instabot version: 0.117.0 - DEBUG - Bot imported from /usr/local/lib/python3.7/dist-packages/instabot/bot/bot.py
instabot version: 0.117.0 - DEBUG - Loading uuids
instabot version: 0.117.0 - INFO - Recovery from /home/pi/config/findanmcar_uuid_and_cookie.json: COOKIE False - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=5d9fefc2-8c72-42d9-b080-455561985772
- uuid=ade27930-38b4-46e7-8c59-6dd220abda53
- client_session_id=4200fba2-2d11-44a5-8b4e-c369e8dc9d9e
- device_id=android-be97a499566ebce3
instabot version: 0.117.0 - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
instabot version: 0.117.0 - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
instabot version: 0.117.0 - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
instabot version: 0.117.0 - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
instabot version: 0.117.0 - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
instabot version: 0.117.0 - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
instabot version: 0.117.0 - DEBUG - Responsecode indicates error; response content: b'{"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/42380627637/8eCa4IvcbP/", "api_path": "/challenge/42380627637/8eCa4IvcbP/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true, "flow_render_type": 0}, "status": "fail", "error_type": "checkpoint_challenge_required"}'
instabot version: 0.117.0 - ERROR - Request returns 400 error!
instabot version: 0.117.0 - INFO - Instagram's error message: challenge_required
instabot version: 0.117.0 - INFO - Error type: checkpoint_challenge_required
root - INFO - found result!
root - INFO - https://images.craigslist.org/00A0A_5J0RGA13PMU_0CI0t2_600x450.jpg
instabot version: 0.117.0 - ERROR - Photo Upload failed with the following response: <Response [403]>
instabot version: 0.117.0 - INFO - Photo '/home/pi/Desktop/CarBot/PyCode/00A0A_5J0RGA13PMU_0CI0t2_600x450.jpg' is not uploaded.
root - INFO - found result!
root - INFO - https://images.craigslist.org/00Y0Y_hsAhBKvO9O9_0ne0nd_600x450.jpg
instabot version: 0.117.0 - ERROR - Photo Upload failed with the following response: <Response [403]>
instabot version: 0.117.0 - INFO - Photo '/home/pi/Desktop/CarBot/PyCode/00Y0Y_hsAhBKvO9O9_0ne0nd_600x450.jpg' is not uploaded.
root - INFO - found result!
root - INFO - https://images.craigslist.org/00M0M_2KadshXRREg_0c6094_600x450.jpg
instabot version: 0.117.0 - ERROR - Photo Upload failed with the following response: <Response [403]>
instabot version: 0.117.0 - INFO - Photo '/home/pi/Desktop/CarBot/PyCode/00M0M_2KadshXRREg_0c6094_600x450.jpg' is not uploaded.
